// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZmFj3SJY2chU0mYoKQYqgG3kB9qQIC3Q',
    appId: '1:32191230194:web:adaa41d12c38864633606b',
    messagingSenderId: '32191230194',
    projectId: 'authenticate-6a3c8',
    authDomain: 'authenticate-6a3c8.firebaseapp.com',
    storageBucket: 'authenticate-6a3c8.appspot.com',
    measurementId: 'G-5ZNFHF4N86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvPOhaDKAqsJonpBnoU-HvTKxF-1OY9go',
    appId: '1:32191230194:android:c03c8fdc4f969c8b33606b',
    messagingSenderId: '32191230194',
    projectId: 'authenticate-6a3c8',
    storageBucket: 'authenticate-6a3c8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZmFj3SJY2chU0mYoKQYqgG3kB9qQIC3Q',
    appId: '1:32191230194:web:dc7dac5bfa2cf24c33606b',
    messagingSenderId: '32191230194',
    projectId: 'authenticate-6a3c8',
    authDomain: 'authenticate-6a3c8.firebaseapp.com',
    storageBucket: 'authenticate-6a3c8.appspot.com',
    measurementId: 'G-C90TCPG750',
  );
}
